### ISSUE TITLE
Diagram needs fixing

### ISSUE THREAD

**Issue by lsnovich** [Stefanie-Saffern/API-Guide-for-Burger-Meal-at-GPM-Diner#17]
The diagram has an issue that needs to be fixed

In each case where you have a decision point (a diamond) 
the yes points right,
the no points down
you need to connect the yes to a rectangle which has an action and then from the bottom of the rectangle, loop back into the workflow.

**Comment by Stefanie-Saffern** [comment]
I uploaded the wrong diagram by mistake.   
The correct diagram is uploaded now.
