### ISSUE TITLE
Diagram description

### ISSUE THREAD

**Issue by lsnovich** [Stefanie-Saffern/API-Guide-for-Burger-Meal-at-GPM-Diner#19]
```This workflow diagram is a flowchart that shows how Burger Meal order is processed on the GPMD API. Each part of the diagram visualizes possible choices of the burger meal and its following steps based on its preceeding choice.```

The description needs some work. Please read it and tweak it. 
Also you flip flop between diagram and flowchart. Please pick one term. The better one is flowchart.

**Comment by Stefanie-Saffern** [comment]
I deleted the old file workflow and changed the README file to read flowchart.
