### ISSUE TITLE
POST property table issue

### ISSUE THREAD

**Issue by lsnovich** [Stefanie-Saffern/API-Guide-for-Burger-Meal-at-GPM-Diner#24]
In your POST property table, the row for bun_quantity needs correcting

1. If it is not required, then you cannot make it that it must be ordered. There is a backwards logic here. Either way is fine - but not this way 
either it is not required and you can order no bun  - ie 0 or none
or it is required and you must order at least 1
2. You need a range for all integers
3. Your table is missing ice
4. the response schema is not needed. Either the response will be 200 or an error.

**Comment by Stefanie-Saffern** [comment]
I made the following fixes:   
* The bun is required.  Must order 1.  
* Ice is not required because there is an option for cans of soda only.  

Outstanding issues:   
* The range for all integers: are they only missing in the POST parameters?  
* Should I take out the response schema table?

**Comment by Stefanie-Saffern** [comment]
@lsnovich please review the changes that I made.
Outstanding issues:

Should I take out the response schema table?
